version: '3'

services:

  trino_connector:
    image: 'trinodb/trino:444'
    hostname: trino
    volumes:
      - ./etc/catalog:/etc/trino/catalog
    ports:
      - '8080:8080'
    depends_on:
      metastore:
        condition: service_healthy
      object_store:
        condition: service_healthy

  object_store:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=pass1234
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD-SHELL", "mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc mb minio/warehouse && mc anonymous set public minio/warehouse"]
      interval: 2s
      timeout: 2s
      retries: 5

  metastore:
    image: postgres:18-alpine3.22
    ports:
      - 5432:5432
    volumes:
      - ./iceberg-setup.sql:/docker-entrypoint-initdb.d/iceberg-setup.sql
    environment:
      - POSTGRES_USER=repl_user
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=iceberg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres-user -d iceberg"]
      interval: 5s
      timeout: 5s
      retries: 5
